services:
  predictive-maintenance-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: predictive-maintenance-api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      # Mount models directory if you have pre-trained models
      - ./api/saved_models:/app/saved_models:ro
      # Mount logs directory (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - predictive-maintenance-network

  streamlit-app:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: predictive-maintenance-streamlit
    environment:
      - API_BASE_URL=http://predictive-maintenance-api:8000
    ports:
      - "8501:8501"
    depends_on:
      - predictive-maintenance-api
    restart: unless-stopped
    networks:
      - predictive-maintenance-network


networks:
  predictive-maintenance-network:
    driver: bridge

volumes:
  prometheus_data:
